server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db_currencies
    username: currencies_user
    password: currenciesPass456!
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

services:
  country-service:
    url: http://localhost:8081
    base-path: /api/v1

logging:
  level:
    currency_service: DEBUG
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
